# Generated by Django 4.2.29 on 2026-03-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('x', models.IntegerField(default=100)),
                ('y', models.IntegerField(default=100)),
                ('color', models.CharField(default='yellow', max_length=20)),
            ],
        ),
    ]
