# Generated by Django 4.2.29 on 2026-04-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='area',
            field=models.CharField(default='desafios', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default='Novo Post-it'),
        ),
    ]
