# Generated by Django 4.2.29 on 2026-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_note_area_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='x',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='y',
            field=models.IntegerField(default=50),
        ),
    ]
