# Generated by Django 4.2.29 on 2026-04-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_note_area_alter_note_color_alter_note_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='area',
            field=models.CharField(default='desafios', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(default='yellow', max_length=20),
        ),
    ]
