# Generated by Django 4.2.29 on 2026-04-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_note_area_alter_note_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='x',
        ),
        migrations.RemoveField(
            model_name='note',
            name='y',
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
